/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Prabath
 */
public class channel extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    String chno;
    ResultSet rs = null;
    DefaultTableModel df = null;

    /**
     * Creates new form channel
     */
    public channel() {
        initComponents();
        conn = DBconnect.connect();
        AutoID();
        LoadDoctor();
        LoadPatient();
        tableLoad();

    }

    public class Doctor {

        String id;
        String name;

        public Doctor(String id, String name) {

            this.id = id;
            this.name = name;

        }

        public String toString() {

            return name;
        }
    }

    public class Patient {

        String id;
        String name;

        public Patient(String id, String name) {

            this.id = id;
            this.name = name;

        }

        public String toString() {

            return name;
        }
    }

    public void LoadDoctor() {

        try {
            pst = conn.prepareStatement("select * from doctor");
            rs = pst.executeQuery();
//             txtdname.removeAll();

            while (rs.next()) {

                txtdname.addItem(new Doctor(rs.getString(1), rs.getString(2)));

            }

        } catch (SQLException ex) {
            Logger.getLogger(channel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void LoadPatient() {

        try {
            pst = conn.prepareStatement("select * from patient");
            rs = pst.executeQuery();
//             txtdname.removeAll();

            while (rs.next()) {

                txtpname.addItem(new Patient(rs.getString(1), rs.getString(2)));

            }

        } catch (SQLException ex) {
            Logger.getLogger(channel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void AutoID() {

        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("select MAX(channelno) from channel");
            rs.next();
            rs.getString("MAX(channelno)");

            if (rs.getString("MAX(channelno)") == null) {

                lblchno.setText("CH001");

            } else {

                long id = Long.parseLong(rs.getString("MAX(channelno)").substring(2, rs.getString("MAX(channelno)").length()));
                id++;
                lblchno.setText("CH" + String.format("%03d", id));

            }

        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }

    public void clear() {

        txtdname.setSelectedIndex(-1);
        txtpname.setSelectedIndex(-1);
        txtroom.setValue(0);
//        txtdate.setDate();

    }

    public void tableLoad() {

//       
//        
        try {
            String sql = "SELECT * FROM channel";

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        lblchno = new javax.swing.JLabel();
        txtdname = new javax.swing.JComboBox();
        txtpname = new javax.swing.JComboBox();
        txtroom = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btncanc = new javax.swing.JButton();
        btncre = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CHANNEL REGISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Channel Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Medium ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Channel No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Channel Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtdate.setBackground(new java.awt.Color(102, 102, 255));
        txtdate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 220, -1));

        lblchno.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lblchno.setForeground(new java.awt.Color(255, 255, 255));
        lblchno.setText("jLabel7");
        jPanel1.add(lblchno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        txtdname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        txtdname.setForeground(new java.awt.Color(255, 255, 255));
        txtdname.setBorder(null);
        jPanel1.add(txtdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, -1));

        txtpname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        txtpname.setForeground(new java.awt.Color(255, 255, 255));
        txtpname.setBorder(null);
        jPanel1.add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 210, -1));

        txtroom.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel1.add(txtroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 490, 430));

        table.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(0, 102, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Channel No", "Doctor Name", "Patient Name", "Room No", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 510, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btncanc.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btncanc.setForeground(new java.awt.Color(0, 102, 204));
        btncanc.setText("Cancel");
        btncanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancActionPerformed(evt);
            }
        });
        jPanel2.add(btncanc);

        btncre.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btncre.setForeground(new java.awt.Color(0, 102, 204));
        btncre.setText("Create");
        btncre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreActionPerformed(evt);
            }
        });
        jPanel2.add(btncre);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btncreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreActionPerformed

        String chno = lblchno.getText();
        Doctor d = (Doctor) txtdname.getSelectedItem();
        Patient p = (Patient) txtpname.getSelectedItem();
        String room = txtroom.getValue().toString();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateformat.format(txtdate.getDate());

        try {
            pst = conn.prepareStatement("insert into channel(channelno,doctorname,patientname,roomno,date)values(?,?,?,?,?)");

            pst.setString(1, chno);
            pst.setString(2, d.id);
            pst.setString(3, p.id);
            pst.setString(4, room);
            pst.setString(5, date);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Channel is created successfully!");
            AutoID();
            clear();
            txtdname.requestFocus();
            tableLoad();

        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }


    }//GEN-LAST:event_btncreActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel d1 = (DefaultTableModel) table.getModel();
        int SelectIndex = table.getSelectedRow();

        chno = d1.getValueAt(SelectIndex, 0).toString();
        btncre.setEnabled(false);

    }//GEN-LAST:event_tableMouseClicked

    private void btncancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancActionPerformed
        
       
     int check = JOptionPane.showConfirmDialog(null, "Do you want to cancel?");

        if (check == 0) {
            df = (DefaultTableModel) table.getModel();
            int selected = table.getSelectedRow();
            String id = (df.getValueAt(selected, 0).toString());
            try {

                String sql = "DELETE FROM channel WHERE channelno='" + chno + "'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Channel deleted!");
                AutoID();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
            }finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

        }
        tableLoad();
        clear();
        
        
    }//GEN-LAST:event_btncancActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncanc;
    private javax.swing.JButton btncre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblchno;
    private javax.swing.JTable table;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox txtdname;
    private javax.swing.JComboBox txtpname;
    private javax.swing.JSpinner txtroom;
    // End of variables declaration//GEN-END:variables
}
