/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Prabath
 */
public class doctor extends javax.swing.JPanel {

    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    DefaultTableModel df = null;

    /**
     * Creates new form patient
     */
    public doctor() {
        initComponents();

    }

    int id;
    String uctype;

    int newid;

    public doctor(int id, String utype) {
        initComponents();

        this.id = id;
        this.uctype = utype;

        newid = id;

        conn = DBconnect.connect();
        AutoID();
        tableLoad();

//        JOptionPane.showMessageDialog(this, newid);
    }

    public void tableLoad() {

//        try {
//            pst = conn.prepareStatement("select * from doctor where logid = ?");
//             pst.setInt(1, newid);
//            rs = pst.executeQuery();
//
//            ResultSetMetaData rsm = rs.getMetaData();
//            int c;
//            c = rsm.getColumnCount();
//
//            DefaultTableModel df = (DefaultTableModel) table.getModel();
//            df.setRowCount(c);
//
//            while (rs.next()) {
//                Vector v2 = new Vector();
//
//                for (int i = 1; i <= c; i++) {
//
//                    v2.add(rs.getString("doctorno"));
//                    v2.add(rs.getString("name"));
//                    v2.add(rs.getString("special"));
//                    v2.add(rs.getString("qualification"));
//                     v2.add(rs.getString("channelfee"));
//                    v2.add(rs.getString("phone"));
//                    v2.add(rs.getString("room"));
//                   
//
//                }
//                
//                df.addRow(v2);
//
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(patient.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
        try {
            String sql = "SELECT * FROM doctor where logid = ?";

            pst = conn.prepareStatement(sql);
            pst.setInt(1, newid);

            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }

    public void clear() {

        txtdname.setText("");
        txtspl.setText("");
        txtqul.setText("");
        txtchfee.setText("");
        txtphone.setText("");
        txtroom.setValue(0);
    }

    public void AutoID() {

        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("select MAX(doctorno) from doctor");
            rs.next();
            rs.getString("MAX(doctorno)");

            if (rs.getString("MAX(doctorno)") == null) {

                lbldno.setText("DS001");

            } else {

                long id = Long.parseLong(rs.getString("MAX(doctorno)").substring(2, rs.getString("MAX(doctorno)").length()));
                id++;
                lbldno.setText("DS" + String.format("%03d", id));

            }

        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtspl = new javax.swing.JTextField();
        txtdname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbldno = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtqul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtchfee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtroom = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Medium ITC", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctor No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Specialization");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        txtspl.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        txtspl.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtspl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 190, -1));

        txtdname.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        txtdname.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 30, 390));

        lbldno.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        lbldno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbldno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, 30));

        txtphone.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 190, 30));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qualification");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtqul.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel1.add(txtqul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, 30));

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Channel fee");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtchfee.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel1.add(txtchfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 190, 30));

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        jPanel1.add(txtroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 50, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 470, 500));

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DOCTOR REGISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        btnupdate.setBackground(new java.awt.Color(255, 255, 255));
        btnupdate.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 102, 204));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate);

        btnadd.setBackground(new java.awt.Color(255, 255, 255));
        btnadd.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 102, 204));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 330, 50));

        table.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        table.setForeground(new java.awt.Color(0, 102, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor No", "Doctor name", "Special", "Qualification", "Channel fee", "Phone", "Room No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 540, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        String dno = lbldno.getText();
        String dname = txtdname.getText();
        String spl = txtspl.getText();
        String qul = txtqul.getText();
        String chfee = txtchfee.getText();
        String phone = txtphone.getText();
        String room = txtroom.getValue().toString();

        try {
            pst = conn.prepareStatement("insert into doctor(doctorno,name,special,qualification,channelfee,phone,room,logid)values(?,?,?,?,?,?,?,?)");
            pst.setString(1, dno);
            pst.setString(2, dname);
            pst.setString(3, spl);
            pst.setString(4, qul);
            pst.setString(5, chfee);
            pst.setString(6, phone);
            pst.setString(7, room);
            pst.setInt(8, newid);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Doctor is added successfully!");
            AutoID();
            clear();
            txtdname.requestFocus();
            tableLoad();

        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }


    }//GEN-LAST:event_btnaddActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        DefaultTableModel d1 = (DefaultTableModel) table.getModel();
        int SelectIndex = table.getSelectedRow();

        lbldno.setText(d1.getValueAt(SelectIndex, 0).toString());
        txtdname.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtspl.setText(d1.getValueAt(SelectIndex, 2).toString());
        txtqul.setText(d1.getValueAt(SelectIndex, 3).toString());

        txtchfee.setText(d1.getValueAt(SelectIndex, 4).toString());
        txtphone.setText(d1.getValueAt(SelectIndex, 5).toString());
        txtroom.setValue(d1.getValueAt(SelectIndex, 6));

        btnadd.setEnabled(false);

    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        clear();
        AutoID();
        btnadd.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        String dno = lbldno.getText();
        String dname = txtdname.getText();
        String spl = txtspl.getText();
        String qul = txtqul.getText();
        String chfee = txtchfee.getText();
        String phone = txtphone.getText();
        String room = txtroom.getValue().toString();

        try {
            pst = conn.prepareStatement("update doctor set name =?, special=?, qualification=?, channelfee=?, phone=?, room=? where doctorno = ?");

            pst.setString(1, dname);
            pst.setString(2, spl);
            pst.setString(3, qul);
            pst.setString(4, chfee);
            pst.setString(5, phone);
            pst.setString(6, room);
            pst.setString(7, dno);
//            pst.setInt(8, newid);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Doctor is updated successfully!");
            AutoID();
            clear();
            txtdname.requestFocus();
            tableLoad();
            btnadd.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(doctor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int check = JOptionPane.showConfirmDialog(null, "Do you want to delete?");

        if (check == 0) {
            df = (DefaultTableModel) table.getModel();
            int selected = table.getSelectedRow();
            String id = (df.getValueAt(selected, 0).toString());
            try {

                String sql = "DELETE FROM doctor WHERE doctorno='" + id + "'";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted!");
                AutoID();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e);
            }finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

        }
        tableLoad();
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldno;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtchfee;
    private javax.swing.JTextField txtdname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtqul;
    private javax.swing.JSpinner txtroom;
    private javax.swing.JTextField txtspl;
    // End of variables declaration//GEN-END:variables
}
