/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.JpanelLoader;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Prabath
 */
public class main extends javax.swing.JFrame {

    JpanelLoader JLoader = new JpanelLoader();

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    int idd;

    String uctype;
    int newid;
    String uname;
    String usertype;

    public main(int id, String username, String utype) {
        initComponents();

        this.uname = username;
        lbluname.setText(username);

        this.usertype = utype;
        lblutype.setText(utype);

        this.newid = id;

        idd = newid;

        uctype = lblutype.getText();

        if (uctype.equals("Doctor")) {

//            patientpanel.setVisible(false);
            patientpanel.setVisible(false);

            createchanpanel.setVisible(false);

            viewprespanel.setVisible(false);

            itempanel.setVisible(false);

            userpanel.setVisible(false);
            repbtn.setVisible(false);

        } else if (uctype.equals("Receptionist")) {

            doctorpanel.setVisible(false);
            viewprespanel.setVisible(false);
            repbtn.setVisible(false);
        } else if (uctype.equals("Pharmacist")) {

            patientpanel.setVisible(false);
            doctorpanel.setVisible(false);
            createchanpanel.setVisible(false);
            viewchanpanel.setVisible(false);
            userpanel.setVisible(false);
            repbtn.setVisible(true);

        }

    }

    public void setColor(JPanel panel) {  // carete set colur method

        panel.setBackground(new Color(0, 204, 204)); //[0,204,204]
    }

    public void resetColor(JPanel panel) { // careate reset colur method

        panel.setBackground(new Color(0, 102, 204)); //[102,102,255]

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        repbtn = new javax.swing.JButton();
        lbluname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logoutpanel = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lbllog = new javax.swing.JLabel();
        itempanel = new javax.swing.JPanel();
        lblcreitem = new javax.swing.JLabel();
        patientpanel = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lblpatient = new javax.swing.JLabel();
        createchanpanel = new javax.swing.JPanel();
        lblcrechan = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblcreuser = new javax.swing.JLabel();
        viewchanpanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblvichan = new javax.swing.JLabel();
        viewdocpanel = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        lblviedoc = new javax.swing.JLabel();
        doctorpanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lbldoctor = new javax.swing.JLabel();
        viewprespanel = new javax.swing.JPanel();
        lblvipres = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelcard = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lblutype = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HOSPITAL MANAGEMENT SYSTEM");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 440, -1));

        repbtn.setBackground(new java.awt.Color(255, 255, 255));
        repbtn.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        repbtn.setForeground(new java.awt.Color(51, 51, 51));
        repbtn.setText("REPORT");
        repbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        repbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repbtnActionPerformed(evt);
            }
        });
        jPanel3.add(repbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 150, 40));

        lbluname.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        lbluname.setForeground(new java.awt.Color(153, 255, 255));
        jPanel3.add(lbluname, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1060, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        logoutpanel.setBackground(new java.awt.Color(0, 102, 204));
        logoutpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutpanelMouseExited(evt);
            }
        });
        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        logoutpanel.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lbllog.setBackground(new java.awt.Color(255, 51, 0));
        lbllog.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lbllog.setForeground(new java.awt.Color(255, 255, 255));
        lbllog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shutdown_32px.png"))); // NOI18N
        lbllog.setText("Logout");
        logoutpanel.add(lbllog, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        itempanel.setBackground(new java.awt.Color(0, 102, 204));
        itempanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itempanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itempanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itempanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itempanelMouseExited(evt);
            }
        });
        itempanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcreitem.setBackground(new java.awt.Color(255, 51, 0));
        lblcreitem.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblcreitem.setForeground(new java.awt.Color(255, 255, 255));
        lblcreitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_file_32px.png"))); // NOI18N
        lblcreitem.setText("Create Item");
        itempanel.add(lblcreitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        patientpanel.setBackground(new java.awt.Color(0, 102, 204));
        patientpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientpanelMouseExited(evt);
            }
        });
        patientpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        patientpanel.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lblpatient.setBackground(new java.awt.Color(255, 51, 0));
        lblpatient.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblpatient.setForeground(new java.awt.Color(255, 255, 255));
        lblpatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wheelchair_32px.png"))); // NOI18N
        lblpatient.setText("Patient");
        lblpatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpatientMouseExited(evt);
            }
        });
        patientpanel.add(lblpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        createchanpanel.setBackground(new java.awt.Color(0, 102, 204));
        createchanpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createchanpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createchanpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createchanpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createchanpanelMouseExited(evt);
            }
        });
        createchanpanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createchanpanelKeyPressed(evt);
            }
        });
        createchanpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcrechan.setBackground(new java.awt.Color(255, 51, 0));
        lblcrechan.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblcrechan.setForeground(new java.awt.Color(255, 255, 255));
        lblcrechan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/create_32px.png"))); // NOI18N
        lblcrechan.setText("Create Channel");
        createchanpanel.add(lblcrechan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        userpanel.setBackground(new java.awt.Color(0, 102, 204));
        userpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userpanelMouseExited(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        userpanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lblcreuser.setBackground(new java.awt.Color(255, 51, 0));
        lblcreuser.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblcreuser.setForeground(new java.awt.Color(255, 255, 255));
        lblcreuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_user_male_32px.png"))); // NOI18N
        lblcreuser.setText("Create User");
        userpanel.add(lblcreuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        viewchanpanel.setBackground(new java.awt.Color(0, 102, 204));
        viewchanpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewchanpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewchanpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewchanpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewchanpanelMouseExited(evt);
            }
        });
        viewchanpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        viewchanpanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lblvichan.setBackground(new java.awt.Color(255, 51, 0));
        lblvichan.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblvichan.setForeground(new java.awt.Color(255, 255, 255));
        lblvichan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_32px.png"))); // NOI18N
        lblvichan.setText("View Channel");
        viewchanpanel.add(lblvichan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        viewdocpanel.setBackground(new java.awt.Color(0, 102, 204));
        viewdocpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewdocpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewdocpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewdocpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewdocpanelMouseExited(evt);
            }
        });
        viewdocpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        viewdocpanel.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lblviedoc.setBackground(new java.awt.Color(255, 51, 0));
        lblviedoc.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblviedoc.setForeground(new java.awt.Color(255, 255, 255));
        lblviedoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doctor_male_32px.png"))); // NOI18N
        lblviedoc.setText("View Doctor");
        viewdocpanel.add(lblviedoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        doctorpanel.setBackground(new java.awt.Color(0, 102, 204));
        doctorpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctorpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doctorpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorpanelMouseExited(evt);
            }
        });
        doctorpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        doctorpanel.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 230, 80));

        lbldoctor.setBackground(new java.awt.Color(255, 51, 0));
        lbldoctor.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lbldoctor.setForeground(new java.awt.Color(255, 255, 255));
        lbldoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medical_doctor_32px.png"))); // NOI18N
        lbldoctor.setText("Doctor");
        doctorpanel.add(lbldoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        viewprespanel.setBackground(new java.awt.Color(0, 102, 204));
        viewprespanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewprespanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewprespanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewprespanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewprespanelMouseExited(evt);
            }
        });
        viewprespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblvipres.setBackground(new java.awt.Color(255, 51, 0));
        lblvipres.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        lblvipres.setForeground(new java.awt.Color(255, 255, 255));
        lblvipres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/treatment_32px.png"))); // NOI18N
        lblvipres.setText("View Prescription");
        viewprespanel.add(lblvipres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(createchanpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(userpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(viewchanpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(viewdocpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(doctorpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(viewprespanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(itempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logoutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(patientpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(createchanpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewchanpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewdocpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(doctorpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewprespanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(itempanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 780));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1060, 60));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 760));

        panelcard.setBackground(new java.awt.Color(255, 255, 255));
        panelcard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Medium ITC", 1, 16), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblutype.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        lblutype.setForeground(new java.awt.Color(102, 102, 102));
        jPanel22.add(lblutype, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        jLabel12.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("User Type");
        jPanel22.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Username");
        jPanel22.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel22.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 20, 90));

        panelcard.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 310, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Torrance-Hospital-HD.jpg"))); // NOI18N
        panelcard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));

        jPanel5.add(panelcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1060, 720));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 790));

        setSize(new java.awt.Dimension(1306, 819));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        user us = new user();
        JLoader.jPanelLoader(panelcard, us);

        setColor(userpanel);
    }//GEN-LAST:event_userpanelMouseClicked

    private void userpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseEntered
        setColor(userpanel);
    }//GEN-LAST:event_userpanelMouseEntered

    private void userpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseExited
        resetColor(userpanel);
    }//GEN-LAST:event_userpanelMouseExited

    private void patientpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientpanelMouseEntered
        setColor(patientpanel);
    }//GEN-LAST:event_patientpanelMouseEntered

    private void doctorpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorpanelMouseEntered
        setColor(doctorpanel);
    }//GEN-LAST:event_doctorpanelMouseEntered

    private void createchanpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createchanpanelMouseEntered
        setColor(createchanpanel);
    }//GEN-LAST:event_createchanpanelMouseEntered

    private void viewchanpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewchanpanelMouseEntered
        setColor(viewchanpanel);
    }//GEN-LAST:event_viewchanpanelMouseEntered

    private void viewprespanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprespanelMouseEntered
        setColor(viewprespanel);
    }//GEN-LAST:event_viewprespanelMouseEntered

    private void itempanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itempanelMouseEntered
        setColor(itempanel);
    }//GEN-LAST:event_itempanelMouseEntered

    private void viewdocpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdocpanelMouseEntered
        setColor(viewdocpanel);
    }//GEN-LAST:event_viewdocpanelMouseEntered

    private void logoutpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseClicked
        int check = JOptionPane.showConfirmDialog(null, "Do you want to Logout?");

        if (check == 0) {

//            System.exit(0);
            login log = new login();
            log.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_logoutpanelMouseClicked

    private void logoutpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseEntered
        setColor(logoutpanel);
    }//GEN-LAST:event_logoutpanelMouseEntered

    private void patientpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientpanelMouseExited
        resetColor(patientpanel);
    }//GEN-LAST:event_patientpanelMouseExited

    private void doctorpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorpanelMouseExited
        resetColor(doctorpanel);
    }//GEN-LAST:event_doctorpanelMouseExited

    private void createchanpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createchanpanelMouseExited
        resetColor(createchanpanel);
    }//GEN-LAST:event_createchanpanelMouseExited

    private void viewchanpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewchanpanelMouseExited
        resetColor(viewchanpanel);
    }//GEN-LAST:event_viewchanpanelMouseExited

    private void viewprespanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprespanelMouseExited
        resetColor(viewprespanel);
    }//GEN-LAST:event_viewprespanelMouseExited

    private void itempanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itempanelMouseExited
        resetColor(itempanel);
    }//GEN-LAST:event_itempanelMouseExited

    private void viewdocpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdocpanelMouseClicked
        viewdoctor vd = new viewdoctor();
        JLoader.jPanelLoader(panelcard, vd);

        setColor(viewdocpanel);
    }//GEN-LAST:event_viewdocpanelMouseClicked

    private void viewdocpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewdocpanelMouseExited
        resetColor(viewdocpanel);
    }//GEN-LAST:event_viewdocpanelMouseExited

    private void logoutpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpanelMouseExited
        resetColor(logoutpanel);
    }//GEN-LAST:event_logoutpanelMouseExited

    private void patientpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientpanelMouseClicked
        patient pat = new patient();
        JLoader.jPanelLoader(panelcard, pat);

        setColor(patientpanel);
    }//GEN-LAST:event_patientpanelMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        main mai = new main();
        mai.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jLabel10MouseClicked

    private void doctorpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorpanelMouseClicked

        if (uctype.equals("Doctor")) {

//              new doctor(idd,uctype).setVisible(true);
            doctor doc = new doctor(idd, uctype);
            JLoader.jPanelLoader(panelcard, doc);

            setColor(doctorpanel);

        }


    }//GEN-LAST:event_doctorpanelMouseClicked

    private void lblpatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseClicked
        patient pat = new patient();
        JLoader.jPanelLoader(panelcard, pat);

        setColor(patientpanel);
    }//GEN-LAST:event_lblpatientMouseClicked

    private void lblpatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseEntered
        setColor(patientpanel);
    }//GEN-LAST:event_lblpatientMouseEntered

    private void lblpatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseExited
        resetColor(patientpanel);
    }//GEN-LAST:event_lblpatientMouseExited

    private void createchanpanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createchanpanelKeyPressed

    }//GEN-LAST:event_createchanpanelKeyPressed

    private void createchanpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createchanpanelMouseClicked
        channel chan = new channel();
        JLoader.jPanelLoader(panelcard, chan);

        setColor(createchanpanel);
    }//GEN-LAST:event_createchanpanelMouseClicked

    private void viewchanpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewchanpanelMouseClicked
        viewChannel vc = new viewChannel(idd);
        JLoader.jPanelLoader(panelcard, vc);

        setColor(viewchanpanel);
    }//GEN-LAST:event_viewchanpanelMouseClicked

    private void itempanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itempanelMouseClicked
        item it = new item();
        JLoader.jPanelLoader(panelcard, it);

        setColor(patientpanel);
    }//GEN-LAST:event_itempanelMouseClicked

    private void viewprespanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprespanelMouseClicked
        viewprescription vp = new viewprescription();
        JLoader.jPanelLoader(panelcard, vp);

        setColor(viewprespanel);
    }//GEN-LAST:event_viewprespanelMouseClicked

    private void repbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repbtnActionPerformed
        report r = new report();
        r.setVisible(true);

    }//GEN-LAST:event_repbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createchanpanel;
    private javax.swing.JPanel doctorpanel;
    private javax.swing.JPanel itempanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcrechan;
    private javax.swing.JLabel lblcreitem;
    private javax.swing.JLabel lblcreuser;
    private javax.swing.JLabel lbldoctor;
    private javax.swing.JLabel lbllog;
    private javax.swing.JLabel lblpatient;
    private javax.swing.JLabel lbluname;
    private javax.swing.JLabel lblutype;
    private javax.swing.JLabel lblvichan;
    private javax.swing.JLabel lblviedoc;
    private javax.swing.JLabel lblvipres;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JPanel panelcard;
    private javax.swing.JPanel patientpanel;
    private javax.swing.JButton repbtn;
    private javax.swing.JPanel userpanel;
    private javax.swing.JPanel viewchanpanel;
    private javax.swing.JPanel viewdocpanel;
    private javax.swing.JPanel viewprespanel;
    // End of variables declaration//GEN-END:variables
}
