/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prabath
 */
public class prescription extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    DefaultTableModel df = null;

    /**
     * Creates new form prescription
     */
    public prescription() {
        initComponents();
    }
    
    String id;
    String docname;
    String newid;
    String newdocname;
    
    public prescription(String chno, String dname) {
        initComponents();
        conn = DBconnect.connect();
        AutoID();
        this.id = id;
        this.docname = dname;
        
        newid = chno;
        newdocname = docname;
        txtchno.setText(newid);
        txtchno.setEnabled(false);
        
    }
    
    public void AutoID() {
        
        try {
            Statement s = conn.createStatement();
            rs = s.executeQuery("select MAX(pid) from prescription");
            rs.next();
            rs.getString("MAX(pid)");
            
            if (rs.getString("MAX(pid)") == null) {
                
                txtpno.setText("PC001");
                
            } else {
                
                long id = Long.parseLong(rs.getString("MAX(pid)").substring(2, rs.getString("MAX(pid)").length()));
                id++;
                txtpno.setText("PC" + String.format("%03d", id));
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(item.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
    }
    
    public void clear() {
        
//        txtpno.setText("");
        txtchno.setText("");
        txtdtype.setText("");
        txtdes.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtchno = new javax.swing.JTextField();
        txtdtype = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdes = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtpno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prescription", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Medium ITC", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prescription No");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desease Type");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtchno.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel2.add(txtchno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        txtdtype.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        jPanel2.add(txtdtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, -1));

        txtdes.setColumns(20);
        txtdes.setFont(new java.awt.Font("Eras Medium ITC", 0, 16)); // NOI18N
        txtdes.setForeground(new java.awt.Color(0, 0, 0));
        txtdes.setRows(5);
        jScrollPane1.setViewportView(txtdes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 90));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 280));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Channel No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtpno.setBackground(new java.awt.Color(255, 255, 255));
        txtpno.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        txtpno.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtpno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 400, 350));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("PRESCRIPTION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("Close");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 90, -1));

        btncreate.setBackground(new java.awt.Color(255, 255, 255));
        btncreate.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        btncreate.setForeground(new java.awt.Color(0, 102, 204));
        btncreate.setText("Create");
        btncreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        setSize(new java.awt.Dimension(604, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        String pno = txtpno.getText();
        String chno = txtchno.getText();
        String dtype = txtdtype.getText();
        String desc = txtdes.getText();
        
        try {
            pst = conn.prepareStatement("insert into prescription(pid,channelno,doctorname,detype,description)values(?,?,?,?,?)");
            pst.setString(1, pno);
            pst.setString(2, chno);
            pst.setString(3, newdocname);
            
            pst.setString(4, dtype);
            pst.setString(5, desc);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Prescription is created successfully!");
            AutoID();
            clear();
            
            txtdtype.requestFocus();
            btncreate.setEnabled(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(patient.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btncreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtchno;
    private javax.swing.JTextArea txtdes;
    private javax.swing.JTextField txtdtype;
    private javax.swing.JLabel txtpno;
    // End of variables declaration//GEN-END:variables
}
